version: "3.9"

services:
  model_serving:
    image: "tensorflow/serving"
    environment:
      MODEL_NAME: "bert_model"
    ports:
      - "8501:8501"
    volumes:
      - type: bind
        source: /Users/johnpoh/Desktop/movie_comment/bert_model/saved_model
        target: /models/bert_model

  model:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8800:8800"
    volumes:
      - /Users/johnpoh/Desktop/movie_comment:/app